console.log('=== Email Click Tracking System ===\n');
console.log('Available commands:\n');
console.log('  Start tracking server:');
console.log('    node server.js\n');
console.log('  Add recipients:');
console.log('    node examples/addRecipients.js\n');
console.log('  Create campaign:');
console.log('    node examples/createCampaign.js\n');
console.log('  Send campaign:');
console.log('    node examples/sendCampaign.js <campaign-id>\n');
console.log('  View report:');
console.log('    node examples/viewReport.js\n');
console.log('Setup instructions:');
console.log('  1. Copy .env.example to .env and configure your settings');
console.log('  2. Start the server: node server.js');
console.log('  3. Add recipients: node examples/addRecipients.js');
console.log('  4. Create a campaign: node examples/createCampaign.js');
console.log('  5. Send the campaign: node examples/sendCampaign.js <campaign-id>');
console.log('  6. View analytics: node examples/viewReport.js');
